### ISSUE TITLE
Errors from Stripe in Billing are not generated, parsed and caught correctly

### ISSUE THREAD

**Issue by phutchins** [Storj/billing#48]
### Tasks
- [ ] Catch all rejected promises from the Promise.all's
- [ ] Fix the error thrown by billing for failed Stripe requests

### Summary

When generating debits, if there is an error when calling out to the Stripe API, the billing-importer script does not catch it.

```
(node:506) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [object Object]
```

This could be caught at the Promise.all like so...

```
        cursor.on('end', () => {
          Promise.all(insertPromises).then(() => {
            resolve(true)
          })
          .catch((err) => {
            console.log('Error processing debits', err);
          })
        })
```

But currently the `err` object returned is not the proper format and is not usable.

```
Error: [object Object]
    at Request._callback (/root/lib/utils/billing-client.js:42:49)
    at Request.self.callback (/root/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by bryanchriswhite** [comment]
We learned that `err` is literally a string of `"Error: [object Object]"` and that this string is coming from the billing api, rather than billing-importer-specific code.

It's most likely to be in a router or a graphql resolver somewhere.

**Comment by RichardLitt** [comment]
Closing as stale. Thank you.
